# Generated by Django 3.0.3 on 2020-03-07 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CMUdashboard', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mask',
            name='image',
            field=models.ImageField(blank=True, upload_to='Item_image'),
        ),
    ]
